Update to require PHP 7.1
reactphp/stream pull request #175
Opened 2024-02-21 11:34 UTC by WyriHaximus

2024-02-23 07:54 UTC, SimonFrings requested changes
Thanks for working on this @WyriHaximus, I added a few remarks down below and I also went through the project and noticed a few things we should add to this PR. Here are my findings and thoughts:

1. First of all, I think my suggested changes will make this PR a lot bigger, so maybe it's a good idea to split the last commit into two. This way the PR is a bit more overseeable. Could be something like:
    - Commit 2: "Update PHP language syntax and remove legacy workarounds" (including all the array stuff)
    - Commit 3: "Update test suite and remove legacy PHPUnit workarounds" (PHPUnit changes + legacy loop extensions in tests)

2. We have a lot of workaround functions inside the `TestCase.php` that were necessary for PHPUnit < 7.5. Tried this out and I think we can get rid of all of them (regarding the `setExpectedException()`, `assertContainsString()`, `assertContainsStringIgnoringCase()` and `assertSameIgnoringCase()`)

3. There are 3 places in our test suite where we skip tests for HHVM, we should also remove them (reagarding the `DuplexResourceStreamTest`, `WritableResourceStreamTest` and `ReadableResourceStreamTest`)

4. Inside the `DuplexResourceStream` and `ReadableResourceStrem` we have legacy PHP 5 workarounds at the bottom which can be removed in my opinion.

5. In line 90 inside the `FunctionalInternetTest` class is a comment describing a bug in PHP < 7.1.4 and PHP < 7.0.18. The part for 7.1.4 should stay, but I think we can remove the part for  PHP < 7.0.18.

That's it for now :+1:

2024-02-23 07:54 UTC, SimonFrings commented on README.md
>  performance improvements.
We started to suggest using the latest supported PHP version instead of just PHP 7+ for our projects, I think it makes sense to also add this here (Similar to [reactphp/cache#58](https://github.com/reactphp/cache/pull/58/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)):

```suggestion
extensions and supports running on PHP 7.1 through current PHP 8+.
It's *highly recommended to use the latest supported PHP version* for this project.

2024-02-23 07:54 UTC, SimonFrings commented on tests/TestCase.php
>          }
I think we should align this with the changes made in https://github.com/reactphp/cache/pull/58/files#diff-abf1fa77a19f720052b75bc802df0260157b9064d8c3c12a80794f01e9acc065

2024-02-23 07:54 UTC, SimonFrings commented on tests/DuplexResourceStreamIntegrationTest.php
> +            }
@clue dropped the deprecated `ExtLibeventLoop` in https://github.com/reactphp/event-loop/pull/273 for EventLoop v3, so I think we don't have to test this here anymore:

```suggestion
            function () {
                return new LibEventLoop();
            }
```

2024-02-23 07:54 UTC, SimonFrings commented on tests/DuplexResourceStreamIntegrationTest.php
> +            }
@clue dropped the deprecated `ExtLibevLoop` in https://github.com/reactphp/event-loop/pull/273 for EventLoop v3, so I think we don't have to test this here anymore:

```suggestion
            function () {
                return new LibEvLoop();
            }
```

2024-02-23 11:42 UTC, WyriHaximus commented on tests/DuplexResourceStreamIntegrationTest.php
> +            }
`LibEventLoop` doesn't exist.

2024-02-23 11:42 UTC, WyriHaximus commented on tests/DuplexResourceStreamIntegrationTest.php
> +            }
`LibEvLoop` doesn't exist.

2024-02-23 11:42 UTC, WyriHaximus commented on tests/DuplexResourceStreamIntegrationTest.php
> +            }
Dropping this one

2024-02-23 11:43 UTC, WyriHaximus commented on tests/DuplexResourceStreamIntegrationTest.php
> +            }
Updated this one to `ExtEvLoop` and will also add `ExtUvLoop`

2024-02-24 13:48 UTC, WyriHaximus commented
Thanks for the pointers @SimonFrings, updated the PR according to them.

2024-02-26 13:18 UTC, SimonFrings approved these changes
Went through everything, looks good to me. Also nice that you caught a few additional things that I didn't even mention :+1:

2024-02-26 21:46 UTC, WyriHaximus commented
Update one small nitpick, and had to bump the macos job a few times until it passed

2024-05-14 18:08 UTC, clue reviewed
@WyriHaximus Thank you for looking into this and for your patience! I've added some minor remarks only, otherwise love the direction!

2024-05-14 18:08 UTC, clue commented on src/DuplexResourceStream.php
> +            });
While I agree this looks *cleaner*, I would suggest keeping the original array in this PR to avoid using an additional closure (stack frame / overhead):

```suggestion
            $this->loop->addReadStream($this->stream, [$this, 'handleData']);
```

That said, I'm happy to discuss this in a separate PR to evaluate this and its potential impact in more depth.

2024-05-14 18:08 UTC, clue commented on src/DuplexResourceStream.php
> +    private function handleData()
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on src/DuplexResourceStream.php
> +        $data = \stream_get_contents($this->stream, $this->bufferSize);
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on src/ReadableResourceStream.php
> +            });
(See above. Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on src/ReadableResourceStream.php
> +    private function handleData()
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on src/WritableResourceStream.php
> +            });
(See above. Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on src/WritableResourceStream.php
> -    /** @internal */
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on tests/DuplexResourceStreamIntegrationTest.php
> +                return \function_exists('uv_loop_new');
Looks reasonable, though potentially unrelated to this PR (https://github.com/reactphp/event-loop/pull/234, https://github.com/reactphp/event-loop/pull/273 and https://github.com/reactphp/event-loop/pull/128). Also, all other function calls in the test suite do not use the global namespace (#137):

```suggestion
                return function_exists('uv_loop_new');
```

2024-05-14 18:08 UTC, clue commented on tests/DuplexResourceStreamIntegrationTest.php
> +                return class_exists('EventBase') && class_exists('React\EventLoop\ExtEventLoop');
Looks like a leftover:

```suggestion
                return class_exists('EventBase');
```

2024-05-14 18:08 UTC, clue commented on tests/DuplexResourceStreamIntegrationTest.php
> +
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on tests/DuplexResourceStreamTest.php
> +
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on tests/DuplexResourceStreamTest.php
> +
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on tests/DuplexResourceStreamTest.php
> +
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on tests/DuplexResourceStreamTest.php
> +
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on tests/DuplexResourceStreamTest.php
> +
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on tests/DuplexResourceStreamTest.php
> +
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on tests/DuplexResourceStreamTest.php
> +
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on tests/ReadableResourceStreamTest.php
> +
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on tests/ReadableResourceStreamTest.php
> +
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on tests/ReadableResourceStreamTest.php
> +
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on tests/ReadableResourceStreamTest.php
> +
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on tests/ReadableResourceStreamTest.php
> +
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on tests/ReadableResourceStreamTest.php
> +
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on tests/ReadableResourceStreamTest.php
> +
(Change no longer needed when above suggestion is applied).

2024-05-14 18:08 UTC, clue commented on tests/ReadableResourceStreamTest.php
> +        $ref->invoke($conn, 'handleData');
(Change no longer needed when above suggestion is applied).

2024-05-14 18:12 UTC, clue commented on tests/DuplexResourceStreamTest.php
> +        $this->expectException('InvalidArgumentException');
Definitely reasonable! I would suggest updating this to the class syntax while we're at it (see also other changes): 

```suggestion
        $this->expectException(\InvalidArgumentException::class);
```

2024-05-15 05:52 UTC, WyriHaximus commented on tests/DuplexResourceStreamTest.php
> +        $this->expectException('InvalidArgumentException');
Hah doh, will also have a look at this for https://github.com/reactphp/event-loop/pull/276 /cc @SimonFrings

2024-05-15 05:53 UTC, WyriHaximus commented on src/DuplexResourceStream.php
> +            });
> That said, I'm happy to discuss this in a separate PR to evaluate this and its potential impact in more depth.

Sounds like a plan :+1:

2024-05-15 13:44 UTC, clue approved these changes
@WyriHaximus Went over your changes together with @SimonFrings and addressed all outstanding issues, great work, now let's get this shipped! :shipit: :shipit: :shipit:

For reference: Link to diff between original 1d047d5a4a550eb86de9a048f5c92bc48d516e2f and new 2f70d54c64641576ec054b08d58a8b0515055771: https://gist.github.com/clue/7e6012fecc995dee201eb3aae600bcfb)

2024-05-15 13:48 UTC, clue commented on tests/DuplexResourceStreamIntegrationTest.php
> +                return \function_exists('uv_loop_new');
I've removed this for now to move forward with the PHP changes, but I agree that we would want to look into this again in a future PR that revisits the event loops as discussed in the tickets linked above.

2024-05-15 14:25 UTC, SimonFrings approved these changes
Went over all changes made, looks good to me so let's get this in :+1:

2024-05-15 14:28 UTC, merged